### ISSUE TITLE
“No such file or directory” Error

### ISSUE THREAD

**Issue by swashcap** [mwittig/npm-license-crawler#2]
Running `npm-license-crawler .` in a directory with a _package.json_ and installed _node_modules_ results in this error:

```shell
env: node\r: No such file or directory
```

* OS: **OS X 10.11.2**
* NPM:  **3.3.12**
* Node: **5.3.0**

**Comment by uglow** [comment]
+1 
Same OS, NPM and Node. Using NVM, changed to Node v4.2.4, same result

**Comment by mwittig** [comment]
OK, I'll have a look at this asap.

**Comment by mwittig** [comment]
Guys, I think the problem is solved with new release. The problem was the published command wrapper file contained CRLF line endings which causes problems specifically on OS X. Seems like a few other node projects had the same issue in the past. Originally, I developed on OS X, but I had to migrate my dev environment to Win 10, recently. On Windows, git will perform an autoconversion to CRLF by default on the local base - I wasn't aware of the consequences it has for OS X users. Sorry about that.

Please provide a short feedback. Thanks

**Comment by mwittig** [comment]
@swashcap and @uglow As you did not get back to me I assume the issue has been solved with the new release. May be the force with you!

**Comment by uglow** [comment]
Hi Marcus,

Sorry for not getting back to you. I used the parent dependency of this package instead, which met my needs at the time. If you  reproduced the error, made changes and couldn't reproduce it anymore, then I agree that it's safe to close this. 

Cheers,
Brett

**Comment by mwittig** [comment]
Hi Brett,

Thanks for letting me know. If you only need to check licenses for a single package (which is the common case, I think) you'll be fine with license-checker. 

Regards
Marcus
